service: tvshows

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  memory: 128m
  profile: default
  stage: dev

custom:
  webpackIncludeModules: true

functions:
  create:
    handler: src/handler.create
    events:
      - http:
          path: ${self:service}
          method: post

  list:
    handler: src/handler.list
    events:
      - http:
          path: ${self:service}
          method: get

  get:
    handler: src/handler.get
    events:
      - http:
          path: ${self:service}/{id}
          method: get

  update:
    handler: src/handler.update
    events:
      - http:
          path: ${self:service}/{id}
          method: put

  delete:
    handler: src/handler.delete
    events:
      - http:
          path: ${self:service}/{id}
          method: delete

plugins:
  - serverless-webpack
  - serverless-offline
